DROP TABLE IF EXISTS Students;
CREATE TABLE IF NOT EXISTS Students(
stud_id INTEGER PRIMARY KEY AUTOINCREMENT,
first_name TEXT,
last_name TEXT
);

DROP TABLE IF EXISTS Quizzes;
CREATE TABLE IF NOT Exists Quizzes(
quiz_id INTEGER PRIMARY KEY AUTOINCREMENT,
subject TEXT,
number_of_questions TEXT,
date_of_quiz TEXT
);

DROP TABLE IF EXISTS Results;
CREATE TABLE IF NOT Exists Results(
res_id INTEGER PRIMARY KEY AUTOINCREMENT,
stu_id INTEGER,
quiz_id INTEGER,
score INTEGER
);
